site_name: Arknights-Mower 文档
site_url: https://arkmowers.github.io/arknights-mower/
repo_name: arkmowers/arknights-mower
repo_url: https://github.com/ArkMowers/arknights-mower
edit_uri: edit/doc-pages/docs/
copyright: This Software is under the terms of MIT License.

theme:
  language: zh
  name: material
  logo: assets/logo/logo.ico
  favicon: assets/logo/logo.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    annotation: material/comma-circle-outline
  features:
    - content.action.edit
    - content.code.copy
    - content.code.select
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - navigation.prune
    - toc.follow
    - search.highlight
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - toc:
      permalink: true
      toc_depth: 5
      anchorlink: true
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.magiclink
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ArkMowers/arknights-mower
    - icon: material/file-document
      link: https://github.com/ArkMowers/arknights-mower/tree/doc-pages

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
  
plugins:
  - search
  - glightbox
  - git-revision-date-localized:
      locale: zh
      enable_creation_date: true
  - git-committers:
      repository: ArkMowers/arknights-mower
      branch: doc-pages
      enabled: !ENV [CI, false]

nav: 
  - 简介: ./README.md
  - Mower入门一条龙:
    - manual/README.md
    - 前言: manual/intro.md
    - 下载及更新: manual/install.md
    - Docker 部署: manual/docker-deploy.md
    - Mower使用: manual/mower-settings.md
    - 排班教学: manual/schedule.md
    - 专精推荐: manual/MasteryRecommendation.md
    - 数据图表: manual/chart.md
    - 常见问题: manual/qa.md
  - 旧版手册:
    - former-manual/README.md
    - 入门指北: 
      - former-manual/manualV2/README.md
      - 前言: former-manual/manualV2/intro.md
      - 下载、运行及更新: former-manual/manualV2/install.md
      - Mower设置: former-manual/manualV2/mower-settings.md
      - MAA设置: former-manual/manualV2/maa-settings.md
      - 排班教学: former-manual/manualV2/schedule.md
      - 常见问题: former-manual/manualV2/qa.md
      - 用户须知: former-manual/manualV2/notice.md
      - 致谢: former-manual/manualV2/appreciate.md
    - 更早的手册:
      - former-manual/manualV1/start/README.md
      - 安装与更新: former-manual/manualV1/start/download.md
      - 基建功能介绍: former-manual/manualV1/start/riic.md
      - 配置指南: 
        - former-manual/manualV1/conf/README.md
        - 设置: former-manual/manualV1/conf/1.setting.md
        - 高级设置: former-manual/manualV1/conf/2.advancedSettings.md
        - 外部调用: former-manual/manualV1/conf/3.externalCall.md
        - 排班表输入规则: former-manual/manualV1/conf/4.planValidation.md
        - 内置设定: former-manual/manualV1/conf/5.buildinSettings.md
        - 副表（beta）: former-manual/manualV1/conf/6.customConditionPlan.md
      - 常见问题: 
        - former-manual/manualV1/qa/README.md
      - 其他说明: 
        - former-manual/manualV1/noun/README.md
        - 名词释义: former-manual/manualV1/noun/1.explanation.md
        - 使用小技巧: former-manual/manualV1/noun/2.tips.md
  - 开发文档: 
    - dev/README.md
    - 开发环境: dev/environment.md
    - 版本与分支: dev/branch.md
    - 项目文档: dev/doc.md
    - 图像处理基础函数: dev/image.md
    - 特征匹配: dev/feature-matching.md
    - 示例:
      - 图像处理示例:
        - 坐标与区域: assets/snippets/coordinate.md
        - 加载图像: assets/snippets/loadimg.md
        - 裁切图像: assets/snippets/cropimg.md
        - 二值化: assets/snippets/thres2.md
      - 特征匹配示例:
        - 特征与特征点: assets/snippets/feature-point.md
        - 特征点的匹配: assets/snippets/feature-matching.md
        - 利用特征匹配定位目标图像: assets/snippets/matcher.md
        - 利用特征匹配定求解单应性矩阵: assets/snippets/feature-matching-3d.md
        - 生息演算地图匹配地点: assets/snippets/ra-map.md
        - 多目标: assets/snippets/multi-matching.md
