[pytest]
testpaths = arknights_mower/tests scripts/tests
python_files = *_tests.py test_*.py
filterwarnings =
    ignore:^Unsupported Windows version \(2025server\)\. ONNX Runtime supports Windows 10 and above, only\.$:UserWarning:^onnxruntime\.capi\.onnxruntime_validation$
