from __future__ import annotations

from arknights_mower.utils.scene import Scene

SCENE_RULES: list[tuple[str, int, object]] = [
    ("connecting", Scene.CONNECTING, None),
    ("confirm", Scene.CONFIRM, None),
    ("order_label", Scene.ORDER_LIST, None),
    ("drone", Scene.DRONE_ACCELERATE, None),
    ("factory_collect", Scene.FACTORY_ROOMS, None),
    ("nav_bar", Scene.NAVIGATION_BAR, None),
    ("read_mail", Scene.MAIL, None),
    ("navigation/record_restoration", Scene.OPERATOR_CHOOSE_LEVEL, None),
    ("fight/refresh", Scene.OPERATOR_SUPPORT, None),
    ("ope_select_start", Scene.OPERATOR_SELECT, None),
    ("ope_eliminate", Scene.OPERATOR_ELIMINATE, None),
    ("ope_elimi_agency_panel", Scene.OPERATOR_ELIMINATE_AGENCY, None),
    ("riic/report_title", Scene.RIIC_REPORT, None),
    ("control_central_assistants", Scene.CTRLCENTER_ASSISTANT, None),
    ("infra_overview", Scene.INFRA_MAIN, None),
    ("room_detail", Scene.INFRA_DETAILS_OPEN, None),
    ("clue", Scene.INFRA_CONFIDENTIAL, None),
    ("infra_overview_in", Scene.INFRA_ARRANGE, None),
    ("arrange_confirm", Scene.INFRA_ARRANGE_CONFIRM, None),
    ("terminal_main", Scene.TERMINAL_MAIN, None),
    ("open_recruitment", Scene.RECRUIT_MAIN, None),
    ("recruiting_instructions", Scene.RECRUIT_TAGS, None),
    ("shop_credit_2", Scene.SHOP_OTHERS, None),
    ("shop_cart", Scene.SHOP_CREDIT_CONFIRM, None),
    ("login_loading", Scene.LOGIN_LOADING, None),
    ("12cadpa", Scene.LOGIN_START, None),
    ("skip", Scene.SKIP, None),
    ("login_connecting", Scene.LOGIN_LOADING, None),
    ("arrange_order_options", Scene.RIIC_OPERATOR_SELECT, None),
    ("mission_trainee_on", Scene.MISSION_TRAINEE, None),
    ("spent_credit", Scene.SHOP_UNLOCK_SCHEDULE, None),
    ("loading7", Scene.LOADING, None),
    ("clue/daily", Scene.CLUE_DAILY, None),
    ("clue/receive", Scene.CLUE_RECEIVE, None),
    ("clue/give_away", Scene.CLUE_GIVE_AWAY, None),
    ("clue/summary", Scene.CLUE_SUMMARY, None),
    ("business_card", Scene.BUSINESS_CARD, None),
    ("friend_list", Scene.FRIEND_LIST, None),
    ("credit_visiting", Scene.BUSINESS_CARD, None),
    ("main_theme", Scene.TERMINAL_MAIN_THEME, None),
    ("ope_plan", Scene.OPERATOR_BEFORE, None),
    ("ope_agency_going", Scene.OPERATOR_ONGOING, None),
    ("ope_agency_fail", Scene.OPERATOR_ONGOING, None),
    ("ope_failed", Scene.OPERATOR_FAILED, None),
    ("ope_finish", Scene.OPERATOR_FINISH, None),
    ("fight/use", Scene.OPERATOR_ONGOING, None),
    ("skill_collect_confirm", Scene.TRAIN_FINISH, None),
    ("pull_once", Scene.HEADHUNTING, None),
    ("loading2", Scene.LOADING, None),
    ("materiel_ico", Scene.MATERIEL, None),
    ("bill_accelerate", Scene.DRONE_ACCELERATE, None),
    ("one_hour", Scene.RECRUIT_TAGS, None),
    ("start", Scene.OPERATOR_CHOOSE_LEVEL, None),
    ("confirm_blue", Scene.INFRA_ARRANGE_ORDER, None),
    ("mission_daily_on", Scene.MISSION_DAILY, None),
    ("mission_weekly_on", Scene.MISSION_WEEKLY, None),
    ("login_button", Scene.INDEX, None),
    ("login_logo", Scene.LOGIN_MAIN, None),
    ("double_confirm/main", Scene.DOUBLE_CONFIRM, None),
]

# Rules with scope parameter
SCOPED_RULES: list[tuple[str, int, tuple]] = [
    ("infra_todo", Scene.INFRA_TODOLIST, ((0, 1013), (241, 1080))),
]

# Custom scene detector names (complex conditions beyond simple find)
CUSTOM_DETECTORS: list[str] = [
    "credit_shop_countdown",
    "login_logo_multi",
    "arrange_order_options_scene",
    "ope_recover_potion_on",
    "ope_recover_originite_on",
    "clue_place",
    "clue_next",
    "all_in",
    "loading3",
    "loading4",
    "loading",
    "ope_agency_lock",
    "next_step",
    "shop_assist",
    "depot",
    "announcement_close",
    "main_theme_small",
    "collection_small",
    "visit_limit",
    "episode",
    "collection",
    "biography",
    "terminal_eliminate",
    "terminal_longterm_reclamation_algorithm",
    "terminal_pre2",
    "enter",
    "upgrade_failure",
    "check_in",
    "close_mine",
    "login_new",
    "login_captcha",
    "login_bilibili",
    "login_bilibili_privacy",
    "upgrade",
    "terminal_longterm",
    "terminal_regular",
    "terminal_periodic",
    "terminal_pre",
    "ra/main_title", "ra/guide_entrance",
    "sf/entrance",
    "sss/main",
]
