pipeline {
    agent any
    
    parameters {
        choice(
            name: 'DEPLOY_ENV',
            choices: ['', 'Res', 'Dev', 'Beta'],
            description: '选择部署环境'
        )
        choice(
            name: 'Target_Path',
            choices: ["/data/MowerUpdate/"],
            description: '选择目标路径'
        )
    }

    stages {

        stage('检查拉取') {
            steps {
                // 多分支流水线会自动拉取代码，这里主要是确认
                echo "当前分支: ${env.BRANCH_NAME}"
                echo "当前部署环境: ${params.DEPLOY_ENV}"
                sh 'ls -la'  // 验证文件是否存在
            }
        }
        
        stage('Build') {
            when {
                not { 
                    equals expected: '', actual: params.DEPLOY_ENV
                }
            }
            steps {
                sh '''
                    cd ui
                    npm install
                    npm run build
                    cd ..
                    python3 -m venv venv
                    . ./venv/bin/activate
                    pip install -r requirements.in
                    pip install Flask flask-cors flask-sock pywebview
                    rm -rf dist
                    pip install pyinstaller
                    pyinstaller webui_zip_for_linux.spec
                '''
            }
        }
        
        stage('执行upgrade.sh') {
            when {
                not { 
                    equals expected: '', actual: params.DEPLOY_ENV
                }
            }
            steps {
                echo "当前分支: ${env.BRANCH_NAME}"
                sh """
                    cd LinuxUpgrade
                    chmod +x MowerUpGradeConsole
                    ./MowerUpGradeConsole ${params.DEPLOY_ENV} ${params.Target_Path}
                """
            }
        }
    }
    
    post {
        always {
            echo "构建完成 - 状态: ${currentBuild.result}"
        }
        success {
            echo " 所有步骤执行成功！"
        }
        failure {
            echo " 构建失败，请检查日志"
        }
    }
}