#!/bin/bash
#
# Runs before git flow release delete
#
# Positional arguments:
# $1    The version ( !!!NOT!!! including the version prefix)
# $2    The origin remote
# $3    The full branch name (including the release prefix)
#
# The following variables are available as they are exported by git-flow:
#
# MASTER_BRANCH - The branch defined as Master
# DEVELOP_BRANCH - The branch defined as Develop

# VERSION=$1
# ORIGIN=$2
# BRANCH=$3

ROOT=`git rev-parse --show-toplevel`
VERSION=$1

rm "$ROOT/doc/CHANGELOG/$VERSION.md"
git reset --hard HEAD
